# AUDIO
SAMPLE_RATE = 16000
CHANNELS = 1
CHUNK_SIZE = 1024

# WHISPER MODEL
STT_MODEL_SIZE = "small"

# LLM (OLLAMA)
OLLAMA_URL = "http://localhost:11434/v1"
LLM_MODEL = "SpeakLeash/bielik-minitron-7B-v3.0-instruct:Q4_K_M"

# VAD
VAD_THRESHOLD = 0.5
VAD_SILENCE_DURATION = 1